---
- name: Post Installation Tasks (Setting up Node Labels)
  hosts: all
  vars_files:
    - ../vars/main.yml

  tasks:
  - name: Install Pre-requisites
    pip:
      name:
        - kubernetes
        - openshift

  - name: Get Nodes with amd64 architecture
    shell: "oc get nodes -l kubernetes.io/arch=amd64 | awk '(NR>1) { print $1 }'"
    register: node_names

  - name: Print Node names with amd64 architecture
    debug:
      msg: "Nodes with amd64 : {{ node_names.stdout_lines }}"

  - name: Add labels defined in node_labels to amd64 Nodes
    kubernetes.core.k8s:
      state: present
      kind: Node
      name: "{{ item }}"
      definition:
        metadata:
          labels: "{{ node_labels }}"
    with_items: "{{ node_names.stdout_lines }}"
